jobs:
  build:
    docker:
      - image: maloubobola/circleci-gcloud-node:latest
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: yarn
      - run:
          name: Build Dependencies
          command: yarn build
      - run: cp .htaccess public/.htaccess
      - run: node .circleci/deploy.js
      - run: echo "WE'RE ONLINE"

workflows:
  version: 2
  deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master