jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: sudo apt install build-essential libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev
      - run: npm install
      - run: npm run build
      - run: cp .htaccess public/.htaccess
      - run: node .circleci/deploy.js
      - run: echo "WE'RE ONLINE"

workflows:
  version: 2
  deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master